<?php

namespace adminBundle\Repository;

/**
 * bibliotecaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bibliotecaRepository extends \Doctrine\ORM\EntityRepository
{
}
