<?php

namespace adminBundle\Repository;

/**
 * biblioteca_categoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class biblioteca_categoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
