<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * CondicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondicionRepository extends \Doctrine\ORM\EntityRepository
{
}
