<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * documento_solicitanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoSolicitanteRepository extends \Doctrine\ORM\EntityRepository
{
}
