<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * EstatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstatusPlanillaRepository extends \Doctrine\ORM\EntityRepository
{
}
