<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * TipoDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
