<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * InstruccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstruccionesRepository extends \Doctrine\ORM\EntityRepository
{
}
