<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * NaruralezaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NaruralezaRepository extends \Doctrine\ORM\EntityRepository
{
}
