<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * NotasRemisionDefinitivasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotasRemisionDefinitivasRepository extends \Doctrine\ORM\EntityRepository
{
}
