<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * PlanillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanillaRepository extends \Doctrine\ORM\EntityRepository {

    function consultar_correlativo($id_tipo_caso) {

        $em = $this->getEntityManager();

        $db = $em->getConnection();

        $query = "select oac.correlativo($id_tipo_caso)";

        $stmt = $db->prepare($query);

        $stmt->execute();

        $correlativo = $stmt->fetch();

        return $correlativo;
    }

    function solicitante_persona($id_persona, $id_documento) {

        $em = $this->getEntityManager();

        $db = $em->getConnection();

        $query = "select * from oac.documento_solicitante as a
where a.id_persona=" . $id_persona; // . " and  a.id_planilla=" . $id_documento;

        $stmt = $db->prepare($query);

        $stmt->execute();

        $existe = $stmt->rowCount();

        return $existe;
    }

    function comboAnalista() {

        $em = $this->getEntityManager();

        $db = $em->getConnection();

        $array['Seleccione'] = '';

        $query = "select a.username, (nombre1 ||' '|| nombre2 ||' '|| apellido1 ||' ' || apellido2) as nombre "
                . "from seguridad.fos_user as a, seguridad.fos_user_user_group as b, seguridad.fos_group as c "
                . "where enabled='t' "
                . "and organizacion=6 "
                . "and a.id=b.user_id "
                . "and b.group_id=c.id "
                . "and c.roles like '%ROLE_VALORARCASO%' "
                . "order by nombre";



        $stmt = $db->prepare($query);

        $stmt->execute();

        $resultado = $stmt->fetchAll();

        foreach ($resultado as $value) {

            $username = $value["username"];
            $nombre = ucwords(strtolower($value["nombre"]));
            $array[$nombre] = $username;
        }

        return array($array, $resultado);
    }
    
    function comboAnalistaReverso() {

        $em = $this->getEntityManager();

        $db = $em->getConnection();

        $array['Seleccione'] = '';

        $query = "select a.username, (nombre1 ||' '|| nombre2 ||' '|| apellido1 ||' ' || apellido2) as nombre "
                . "from seguridad.fos_user as a, seguridad.fos_user_user_group as b, seguridad.fos_group as c "
                . "where enabled='t' "
                . "and organizacion=6 "
                . "and a.id=b.user_id "
                . "and b.group_id=c.id "
                . "and c.roles like '%ROLE_EDITARCASO%' "
                . "order by nombre";

        

        $stmt = $db->prepare($query);

        $stmt->execute();

        $resultado = $stmt->fetchAll();

        foreach ($resultado as $value) {

            $username = $value["username"];
            $nombre = ucwords(strtolower($value["nombre"]));
            $array[$nombre] = $username;
        }

        return array($array, $resultado);
    }

    function consultar_dias_feriados() {

        $em = $this->getEntityManager();

        $db = $em->getConnection();

        $query = "select fecha from generico.dias_feriados";

        $stmt = $db->prepare($query);

        $stmt->execute();

        $resultado = $stmt->fetchAll();

        foreach ($resultado as $value) {

            $fecha = $value["fecha"];
            $dias_feriados[] = $fecha;
        }

        return $dias_feriados;
    }

    function comboInstrucciones() {

        $em = $this->getEntityManager();

        $db = $em->getConnection();

        $query = "select id, initcap(nombre) as nombre from generico.instrucciones";

        $stmt = $db->prepare($query);

        $stmt->execute();

        $resultado = $stmt->fetchAll();

        foreach ($resultado as $value) {

            $id = $value["id"];
            $nombre = $value["nombre"];
            $array[$nombre] = $id;
        }

        return array($array);
    }

    function array_instrucciones($json_instrucciones) {

        $em = $this->getEntityManager();

        $db = $em->getConnection();

        $query = "select * from generico.instrucciones";

        $stmt = $db->prepare($query);

        $stmt->execute();

        $elementos = $stmt->rowCount();

        for ($i = 1; $i <= $elementos; $i++) {

            if (in_array($i, $json_instrucciones)) {

                $array[$i] = 1;
            } else {

                $array[$i] = 0;
            }
        }

        return $array;
    }

    

}
