<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * TipoCasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoCasoRepository extends \Doctrine\ORM\EntityRepository
{
    
    function InicializarCorrelativo($id_tipo_caso){
        
        $em = $this->getEntityManager();

        $db = $em->getConnection();

        $existe = 0;
        
        $query = "INSERT INTO oac.correlativo_requerimiento(id_tipo_caso, correlativo)"  
                ."VALUES (".$id_tipo_caso.", 0);";

            $stmt = $db->prepare($query);
            
            $stmt->execute();
            
            $existe = $stmt->rowCount();
            
           return $existe;
        
    }
    
}
