<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * TipoCasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAtencionRepository extends \Doctrine\ORM\EntityRepository
{
    
}
