<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * ValoracionOACRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoracionOACRepository extends \Doctrine\ORM\EntityRepository {

    function descripcionCompetencia($nombre, $competencia) {

        $em = $this->getEntityManager();

        $db = $em->getConnection();

        if ($competencia == 1) {

            $query = "select translate(nombre,'ÁÉÍÓÚáéíóú', 'AEIOUaeiou') as nombre, id from generico.organizaciones "
                    . "where translate(nombre,'ÁÉÍÓÚáéíóú', 'AEIOUaeiou') "
                    . "ILIKE translate('%" . $nombre . "%', 'ÁÉÍÓÚáéíóú', 'AEIOUaeiou') "
                    . "and dependencia=3 and estatus=1";
        }
        if ($competencia == 2) {

            $query = "select initcap(translate(des_ente,'ÁÉÍÓÚáéíóú', 'AEIOUaeiou')) as nombre, id_ente as id from generico.ente "
                    . "where translate(des_ente,'ÁÉÍÓÚáéíóú', 'AEIOUaeiou') "
                    . "ILIKE translate('%" . $nombre . "%', 'ÁÉÍÓÚáéíóú', 'AEIOUaeiou') and id_ente not in(1,3130,4474,4946) and sta_ente='ACT'";
        }

        $stmt = $db->prepare($query);

        $stmt->execute();

        $resultado = $stmt->fetchAll();

        return $resultado;
    }

    function descripcionReferenciaNormativa($nombre) {


        $em = $this->getEntityManager();

        $db = $em->getConnection();

        $query = "select (initcap(translate(nombre,'ÁÉÍÓÚáéíóú', 'AEIOUaeiou')) || '. Fecha Gaceta: '||to_char(fecha, 'dd/mm/yyyy')) as nombre, id from generico.referencias_normativas "
                . "where translate(nombre,'ÁÉÍÓÚáéíóú', 'AEIOUaeiou') "
                . "ILIKE translate('%" . $nombre . "%', 'ÁÉÍÓÚáéíóú', 'AEIOUaeiou') "
                . "and estatus=1";
        
        

        $stmt = $db->prepare($query);

        $stmt->execute();

        $resultado = $stmt->fetchAll();

        return $resultado;
    }
    
    function analistaValoracion($id_planilla){
        
        $em = $this->getEntityManager();

        $db = $em->getConnection();
        
        $query="SELECT 'Analista que inició la valoración' as descripcion, e.created, (nombre1 ||' ' ||nombre2 ||' '|| apellido1 ||' '|| apellido2) as nombre_analista "
                ."FROM oac.estatus_documento as e, seguridad.fos_user as f "
                ."where e.id=(SELECT min(id) FROM oac.estatus_documento where id_documento=".$id_planilla." and id_estatus=5) "
                ."and analista_asignado=username "
                . "union "
                . "SELECT 'Analista que finalizó la valoración' as descripcion, e.created, (nombre1 ||' ' ||nombre2 ||' '|| apellido1 ||' '|| apellido2) as nombre_analista "
                ."FROM oac.estatus_documento as e, seguridad.fos_user as f "
                ."where e.id=(SELECT max(id) FROM oac.estatus_documento where id_documento=".$id_planilla." and id_estatus=5) "
                ."and analista_asignado=username "
                . "order by created";
        
        
        
        $stmt = $db->prepare($query);

        $stmt->execute();

        $resultado = $stmt->fetchAll();

        return $resultado;
        
    }
    
    function analistaPDF($id_planilla, $id_estatus){
        
        $em = $this->getEntityManager();

        $db = $em->getConnection();
        
        $query="SELECT e.created, (nombre1 ||' ' ||nombre2 ||' '|| apellido1 ||' '|| apellido2) as nombre_analista "
                ."FROM oac.estatus_documento as e, seguridad.fos_user as f "
                ."where e.id=(SELECT max(id) FROM oac.estatus_documento where id_documento=".$id_planilla." and id_estatus=".$id_estatus. ")"
                ."and analista_asignado=username";
        
        
        $stmt = $db->prepare($query);

        $stmt->execute();

        $resultado = $stmt->fetch();

        return $resultado;
        
    }
    
    function array_edo_mun_pquia($id_ente) {

        $em = $this->getEntityManager();

        $db = $em->getConnection();

        $query = "SELECT des_edo as estado, des_muni as municipio, des_parro as parroquia "
                . " FROM generico.estados as e, oac.enlace_ente_externo as en, generico.municipio as mun, generico.parroquias as pa "
                . " where en.id_ente=" . $id_ente . " "
                . " and e.id_edo=en.id_estado "
                . " and mun.id_edo=en.id_estado"
                . " and mun.id_muni=en.id_municipio"
                . " and pa.id_edo=en.id_estado"
                . " and pa.id_muni=en.id_municipio"
                . " and pa.id_parro=en.id_parroquia";

        $stmt = $db->prepare($query);

        $stmt->execute();

        $resultado = $stmt->fetch();  
       

        return $resultado;
        
        
    }

}
