<?php

namespace Fgimenez\PlanillaBundle\Repository;

/**
 * ValoracionReferenciasNormativasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoracionReferenciasNormativasRepository extends \Doctrine\ORM\EntityRepository
{
}
