Fgimenez\TestBundle\Entity\AbstractLogEntry:
    type: mappedSuperclass
    table: null
    gedmo:
        ipTraceable: true
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        action:
            type: string
            length: 8
            
        loggedAt:
            type: datetime            
            
        objectId:
            type: string
            length: 64
            nullable: true
            
        objectClass:
            type: string
            length: 255    
            
        version:
            type: integer
        
        data:
            type: array
            nullable: true    
            
        username:
            type: string
            length: 255
            nullable: true      
        
        createdFromIp:
          type: string
          length: 45
          nullable: true
          gedmo:
            ipTraceable:
              on: create
              