Fgimenez\TestBundle\Entity\Catalogo:
    type: mappedSuperclass
    table: null   
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
            unique: true
        descripcion:
            type: text
            nullable: true
        status:
            type: boolean
            
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
        createdAt:
            type: datetime
            column: created_at
            options:
                default: now()
        ultimoUsuario:
            type: string
            length: 255
            column: ultimo_usuario
            options:
                default: ''
    lifecycleCallbacks:     
        prePersist: [setCreatedAtValue]
        preUpdate:  [setUpdatedAtValue]        
