<?php

namespace bulkBundle\Repository;

/**
 * correoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class correoRepository extends \Doctrine\ORM\EntityRepository
{
}
