tipocaso:
    path:  /
    defaults: { _controller: "FgimenezPlanillaBundle:TipoCaso:index" }

tipocaso_show:
    path:  /{id}/show
    defaults: { _controller: "FgimenezPlanillaBundle:TipoCaso:show" }

tipocaso_new:
    path:  /new
    defaults: { _controller: "FgimenezPlanillaBundle:TipoCaso:new" }

tipocaso_create:
    path:  /create
    defaults: { _controller: "FgimenezPlanillaBundle:TipoCaso:create" }
    requirements: { _method: post }

tipocaso_edit:
    path:  /{id}/edit
    defaults: { _controller: "FgimenezPlanillaBundle:TipoCaso:edit" }

tipocaso_update:
    path:  /{id}/update
    defaults: { _controller: "FgimenezPlanillaBundle:TipoCaso:update" }
    requirements: { _method: post|put }

tipocaso_delete:
    path:  /{id}/delete
    defaults: { _controller: "FgimenezPlanillaBundle:TipoCaso:delete" }
    requirements: { _method: post|delete }
    
tipocaso_by_id_delete:
    path:  /delete/{id}
    defaults: { _controller: "FgimenezPlanillaBundle:TipoCaso:deleteById" }
    requirements: { _method: get }
    

tipocaso_bulk_action:
    path:  /bulk-action
    defaults: { _controller: "FgimenezPlanillaBundle:TipoCaso:bulk" }
    requirements: { _method: post }
    
